name: CICD

# Permisos para que github-actions[bot] pueda hacer push a gh-pages
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:

  # 1. JOB BUILD (con 7 pasos)
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./orders_app

    steps:
      # 1. Checkout
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Instalar dependencias
      - name: Install deps
        run: pip install -r requirements.txt

      # 4. Pruebas de integración
      - name: Run tests
        run: python -m pytest test_integration_with_fake.py -v

